### ISSUE TITLE
invalid reference format...

### ISSUE THREAD

**Issue by mollymca** [NCAR/wrf_hydro_docker#53]
Trying to go through the steps on https://hub.docker.com/r/wrfhydro/wps/
When I try to run the command docker run -v ~/dockerMount:/home/docker/mount \
I get "invalid reference format"

Not sure if this is an issue with the container/image etc or Docker.

The expected result should be that I can continue to enter the rest of the commands.

**Comment by jmills-ncar** [comment]
This is due to the ~ expansion, it is not allowed in docker. I have changed hte mkdir command to not use ~ so it is less confusing to users.

**Comment by mollymca** [comment]
I tried the current command mkdir /home/dockerMount
 and it didn't work for me. Also, I'm on a Windows machine... not sure if that matters.

**Comment by mollymca** [comment]
disregard last comment... I got it to create the directory

**Comment by jmills-ncar** [comment]
This is due to a malformed docker run command. Windows powershell does not like `\` new line escape characters used in the example command online
