### ISSUE TITLE
Erro WRF-Hydro V5 in Standalone Mode

### ISSUE THREAD

**Issue by eliascho** [NCAR/wrf_hydro_docker#97]
rm -f CPL_WRF.o CPL_WRF.mod CPL_WRF.stb *~ *.f
cpp -P -xassembler-with-cpp -traditional -DMPP_LAND -I"../Data_Rec" -DWRF_HYDRO   -DWRFIO_NCD_LARGE_FILE_SUPPORT     -I/home/eleazar/wrflib/netcdf/include CPL_WRF.F > CPL_WRF.f
mpif90   -o CPL_WRF.o -w -c -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -I"./" -I"../../MPP" -I"../MPP" -I"../mod" CPL_WRF.f
Warning: Nonexistent include directory "../../MPP"

**Comment by jmccreight** [comment]
is this relevant to this repository?
There is insufficient information to do anything with this. For example, I dont know what container you are referencing.

**Comment by eliascho** [comment]
orry, when I try to compile "./compile_offline_Noah.sh setEnvar.sh" it shows the following line: Warning: Nonexistent include directory "../../MPP", but the MPP folder does exist.

**Comment by jmccreight** [comment]
This is still  incomplete. And not relevant to this repository. You should contact model user support. 
A few tips before you go, 
0) configure (at least show it)
1) I'm not sure the Noah compile script works this way. and /or v5.0 may have been before the compile script accepted that argument. I suggest `source template/setEnvars.sh; ./compile_offline_Noah.sh`. I would test it for NoahMP first (we use this more often), once it works switch to Noah.

**Comment by jmccreight** [comment]
Do that stuff before contacting user support and you will get further faster.

**Comment by eliascho** [comment]
Thank you for the attention, I will follow your suggestions and I will send you my comments.
